import type { Metadata } from 'next'
import './globals.css'
import Header from '../component/nav and footer/Header'
import Footer from '../component/nav and footer/Footer'
import WhatsApp from './whatsapp/page'
export const metadata: Metadata = {
  title: 'BISU GLOBAL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  >
        <Header/>
       <div className='bg-gray-300  '>{children}</div>
        <div className=''> <Footer/></div>
        <div className=''><WhatsApp/></div>
        </body>
    </html>
  )
}
